ods_dk_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      database: ods_eu_dev
      warehouse: ODS_EU_WH
      schema: ODS_DK_IN
      role: ACCOUNTADMIN
      threads: 4
      client_session_keep_alive: false
      query_tag: dbt_ods_dk