ods_dk_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: ods_eu_dev
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'ODS_EU_WH') }}"
      schema: ODS_DK_IN
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DEV_ROLE') }}"
      threads: 4
      client_session_keep_alive: false
      query_tag: "dbt_ods_dk"
