CREATE DATABASE IF NOT EXISTS ods_eu_dev;

CREATE SCHEMA IF NOT EXISTS ods_eu_dev.ODS_DK_IN;
CREATE SCHEMA IF NOT EXISTS ods_eu_dev.ODS_DK_OUT;

CREATE WAREHOUSE IF NOT EXISTS ODS_EU_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD';
